main: getToken.c
	clear
	gcc -o token getToken.c
	./token test.txt

debug:
	clear
	gcc -g getToken.c
	gdb a.out

path: getPath.c
	clear
	gcc -o path getPath.c
	./path path.txt

dpath:
	clear
	gcc -g getPath.c
	gdb a.out

lines:
	clear
	gcc -o lines fgets.c
	./lines lines.txt
